### ISSUE TITLE
dcs-input-command-injector 1.0.7 breaks heading in KA-50

### ISSUE THREAD

**Issue by Schlomo1933** [Quaggles/dcs-input-command-injector#3]
the new update breaks the navigation in KA-50 on all maps. Headingtape and Map turn with a big delay if u start turning the Helicopter.

**Comment by Quaggles** [comment]
I'm having a hard time replicating this, do you have a track?

**Comment by Schlomo1933** [comment]
He Quaggles, I’m really sorry. Your injector mod is not the reason for the ka-50 problems. It’s a new bug caused by version 2.8 that I discovered.Map and headingtape turn in the wrong direction while turning the helicopter after 2.8forum.dcs.worldPlease delete the issue command from me.Your mod works great. And thank u very much for your efforts for the community.But one question pls. I don’t know if u are the right person for that. Can u change the code for Ka-50 route mode? To make this a switch instead a toggle command Von meinem iPhone gesendetAm 05.11.2022 um 14:32 schrieb Quaggles ***@***.***>:﻿
I'm having a hard time replicating this, do you have a track?

**Comment by Quaggles** [comment]
Unfortunately I don't think so, the only command for it that I can see is `iCommandPlane_RouteMode`, there are no `On` or `Off` variants, I've also tried `value_down = 1, value_up = 0`  but each press just toggles it so I don't think ED has provided that functionality, compare that to the landing gear where the following works
```lua
{down = iCommandPlaneGearUp, name = 'Gear Up', category = 'Quaggles Custom'},
{down = iCommandPlaneGearDown, name = 'Gear Down', category = 'Quaggles Custom'},
```
