### ISSUE TITLE
Axis tune window won't open

### ISSUE THREAD

**Issue by chazmat** [Quaggles/dcs-input-command-injector#7]
Axis tune in controls settings doesn't work for me anymore, If I exit DCS and disable the injector, and start DCS again, it's all fine. It's just a minor annoyance though.
Cheers, lovin' it!

**Comment by Quaggles** [comment]
Hi sorry for the late response, the axis tune window works on my side with DCS version 2.9.1.48335 and Input Injector version 1.0.10, what versions are you running and can you attach your DCS log from "C:\Users\<USERNAME>\Saved Games\DCS\Logs\dcs.log"
