### ISSUE TITLE
Aerges Mirage F1 keybinds are empty

### ISSUE THREAD

**Issue by chazmat** [Quaggles/dcs-input-command-injector#8]
When the mod is enabled all keybinds for all three Mirage F1s are empty. This is only a problem with the F1. I have all modules, and I checked them all.

**Comment by Quaggles** [comment]
Working for me with DCS version 2.9.1.48335 and Input Injector version 1.0.10, can you attach your DCS log from "C:\Users<USERNAME>\Saved Games\DCS\Logs\dcs.log".
![image](https://github.com/Quaggles/dcs-input-command-injector/assets/8382945/cac4cd95-0d09-48b7-84cc-77e3f22738c8)
