### ISSUE TITLE
Doesn't work on latest open beta

### ISSUE THREAD

**Issue by amadeus** [Quaggles/dcs-input-command-injector#9]
Looks like the current release is no longer compatible with the current openbeta (and now possibly stable) releases?

**Comment by Quaggles** [comment]
Works for me with DCS version 2.9.1.48335 and Input Injector version 1.0.10, can you attach your DCS log from "C:\Users<USERNAME>\Saved Games\DCS\Logs\dcs.log"?

**Comment by amadeus** [comment]
Actually I think what happened, all my custom binds got somehow undone, I think the problem is here between keyboard and chair.
